### ISSUE TITLE
Cannot install pyterminalsize under Windows with Cmder

### ISSUE THREAD

**Issue by Lucas-C** [asottile/pyterminalsize#1]
There is my `pip3.4 install` output:
```
  Using cached pyterminalsize-0.1.0.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Temp\pip-build-myc65kv9\pyterminalsize\setup.py", line 13, in <module>
        vs = sorted(versions, key=lambda s: int(re.search('\d+', s).group()))[-1]
    IndexError: list index out of range
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "C:\Temp\pip-build-myc65kv9\pyterminalsize\setup.py", line 13, in <module>

        vs = sorted(versions, key=lambda s: int(re.search('\d+', s).group()))[-1]

    IndexError: list index out of range

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Temp\pip-build-myc65kv9\pyterminalsize
```

It looks like I don't have any VisualStudio ComnTools variable in my environment:
https://github.com/asottile/pyterminalsize/blob/master/setup.py#L9

**Comment by asottile** [comment]
Hmmmm usually those environment variables are necessary to build c extensions.  Are you able to install things like simplejson, coverage (with the speedups)? I could also look into building wheels for this similar to what we do in https://github.com/dahlia/libsass-python

**Comment by Lucas-C** [comment]
Yes, I tested and I successfully installed the simplejson & coverage packages

**Comment by asottile** [comment]
Did they install their speedups? This packages will optionally install without the c bits

**Comment by Lucas-C** [comment]
I don't think so, but it was `Using cached wheel link: file:///.../simplejson-3.8.2-cp27-none-win_amd64.whl` (same for `coverage-4.1-cp27-none-win_amd64.whl`)

Note that I do have "Microsoft Visual C++ 2010 x64 Redistributable" installed.

A colleague of mine was hit the same problem today, while trying to install the latest `pre-commit` version using Mingw64 console from "Git for windows".
In other cases, with pre-commit maybe, I saw console messages indicating to install "Visual C++ 2010" package. Could it be possible to add such error message here, possibly in red ?

**Comment by asottile** [comment]
Yeah probably, or I could just build wheels for these.  I think {2.7, 3.4, 3.5} x {win32, win64} should cover most cases?

**Comment by asottile** [comment]
I've uploaded windows wheels, you shouldn't need a C compiler now: https://pypi.python.org/pypi/pyterminalsize

**Comment by asottile** [comment]
@Lucas-C can you confirm that installation works now?

**Comment by Lucas-C** [comment]
```
> pip install --no-cache pyterminalsize
Collecting pyterminalsize
InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading pyterminalsize-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\temp\pip-build-hefam9\pyterminalsize\setup.py", line 13, in <module>
        vs = sorted(versions, key=lambda s: int(re.search('\d+', s).group()))[-1]
    IndexError: list index out of range
```
:(

**Comment by Lucas-C** [comment]
```
> pip install --no-cache --only-binary :all: pyterminalsize
Collecting pyterminalsize
  Could not find a version that satisfies the requirement pyterminalsize (from versions: )
No matching distribution found for pyterminalsize
```

**Comment by Lucas-C** [comment]
> pip --version
pip 7.1.2 from d:\users\lucas_cimon\.local\share\virtualenvs\pre-commit-bug-379\lib\site-packages (python 2.7)
> wmic os get osarchitecture
OSArchitecture
64-bit

**Comment by asottile** [comment]
Ah I uploaded pip8 wheels, can you try that?

**Comment by Lucas-C** [comment]
Nope, it stil doesn't look for the wheel, event with `--no-cache --use-wheel`

**Comment by Lucas-C** [comment]
It looks standard:
```
>> python3.4 -c "import sys; print(sys.platform)"
win32
>> python3.4 -c "import os; print(os.name)"
nt
```

**Comment by Lucas-C** [comment]
I retried outside my virtualenv, with pip v8.1.2 and it worked !
`  Downloading pyterminalsize-0.1.0-cp27-cp27m-win_amd64.whl`
Thanks a lot ;)

**Comment by asottile** [comment]
Woot woot!

**Comment by asottile** [comment]
I'll upload pip 7 wheels when I get to a computer

**Comment by asottile** [comment]
pip7 wheels should be up now, can you try pip7 as well?

**Comment by asottile** [comment]
Here's the final script I used to build all of them: https://gist.github.com/asottile/79958893d1f2db13bc42d3f74f84aef3

**Comment by Lucas-C** [comment]
It works with pip 7.1.2 :)
Thanks a lot !
