### ISSUE TITLE
Windows python2.7 wheels are depended on vs2015 redistributable

### ISSUE THREAD

**Issue by fruch** [asottile/pyterminalsize#2]
it's not the same one as the python2.7 itself is depended on,
it should at least be documented

**Comment by asottile** [comment]
Oops. That was unintentional.  Since I don't think I can replace the existing files on pypi, I'll release a new version and try and build the wheels on a more blank vm.

**Comment by fruch** [comment]
I was trying to use newer versions of precommit which depends it, it wasn't working for me for a long time, yesterday I've found the time to dig in.

Thanks for the quick response

**Comment by fruch** [comment]
BTW b I see you are using appvoer isn't their windows installation is clean enough to build ?

**Comment by asottile** [comment]
appveyor installs a bunch of versions of visual studio and the way I've configured setup.py is it'll pick whatever the latest available is (which seems to be significantly more reliable than expecting any specific vc distributable).

I'll rebuild these with the vc download that python suggests

**Comment by asottile** [comment]
This is probably less of an issue now that 0.9.2 no longer depends on pyterminalsize.

That said, I did try and rebuild these and was having a very difficult time with the python 3 redistributable.  py27 was pretty easy to build however :)

**Comment by asottile** [comment]
I'm not planning to fix this
